name: "Create and Push Docker Image"

on:
  push:
    branches:
      - production
    paths-ignore:
      - "*.md"
      - ".gitignore"
      - ".gitattributes"
  workflow_dispatch:
    branches:
      - production
    paths-ignore:
      - "*.md"
      - ".gitignore"
      - ".gitattributes"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/setup-python@v2
        with:
          python-version: "2.7"
          architecture: "x64"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: markustheort/fia-bot:latest
